import { Asset } from './types';

export const INITIAL_ASSETS: Asset[] = [
  {
    id: 'FOOLAD',
    enName: 'Mobarakeh Steel',
    faName: 'فولاد مبارکه',
    category: 'metals',
    price: 0.082,
    change: 2.4,
    flag: 'ir',
    locationEn: 'Isfahan, Iran',
    locationFa: 'اصفهان، ایران',
    progress: 82,
    descriptionEn: 'Mobarakeh Steel Complex is the largest steelmaker in the Middle East and North Africa, producing flat steel products with over 50% market share in Iran.',
    descriptionFa: 'شرکت فولاد مبارکه بزرگ‌ترین مجتمع صنعتی ایران و بزرگ‌ترین تولیدکننده فولاد تخت در خاورمیانه و شمال آفریقاست که سهم ۵۰ درصدی از بازار داخلی را در اختیار دارد.',
    backingEn: '100% Backed by audited physical hot & cold-rolled steel coils stored in Isfahan certified vaults.',
    backingFa: 'پشتوانه ۱۰۰٪ فیزیکی کلاف‌های فولادی نورد گرم و سرد حسابرسی‌شده در انبارهای رسمی اصفهان.',
    custodianEn: 'Tejarat Custody Vaults & IME Warehouse System',
    custodianFa: 'انبار رسمی بورس کالای ایران و صندوق امانات بانک تجارت',
    riskLevel: 'Low',
    payoutIntervalEn: 'Quarterly Cash Dividend',
    payoutIntervalFa: 'توزیع سود نقدی سه‌ماهه',
    bourseSymbol: 'فولاد',
    tsetmcUrl: 'https://tsetmc.com/instCode/35700344742885862'
  },
  {
    id: 'FMILI',
    enName: 'National Copper',
    faName: 'ملی مس ایران',
    category: 'metals',
    price: 0.115,
    change: 1.8,
    flag: 'ir',
    locationEn: 'Kerman, Iran',
    locationFa: 'کرمان، ایران',
    progress: 91,
    descriptionEn: 'National Iranian Copper Industries Co. operates Sarcheshmeh & Sungun mines, holding top global rank in high-purity electrolytic copper cathodes.',
    descriptionFa: 'شرکت ملی صنایع مس ایران مالک معادن عظیم سرچشمه، سونگون و میدوک، از سودآورترین تولیدکنندگان کاتد مس با خلوص ۹۹.۹۹٪ در منطقه است.',
    backingEn: 'Physical LME-grade copper cathodes (99.99% purity) verified by independent inspectors.',
    backingFa: 'کاتد مس با خلوص ۹۹.۹۹٪ مطابق استاندارد بورس فلزات لندن با گواهی بازرسی مستقل.',
    custodianEn: 'Sarcheshmeh Refinery Depository',
    custodianFa: 'مخزن رسمی مجتمع مس سرچشمه و بانک رفاه',
    riskLevel: 'Low',
    payoutIntervalEn: 'Semi-annual Payout',
    payoutIntervalFa: 'توزیع سود شش‌ماهه',
    bourseSymbol: 'فملی',
    tsetmcUrl: 'https://tsetmc.com/instCode/35425587644337450'
  },
  {
    id: 'ZOB',
    enName: 'Zob Ahan Isfahan',
    faName: 'ذوب آهن اصفهان',
    category: 'metals',
    price: 0.041,
    change: -1.2,
    flag: 'ir',
    locationEn: 'Isfahan, Iran',
    locationFa: 'اصفهان، ایران',
    progress: 64,
    descriptionEn: 'Isfahan Steel Mill is the pioneer of blast furnace steel production in Iran, specializing in structural long products, rails, and rebar.',
    descriptionFa: 'شرکت ذوب‌آهن اصفهان اولین و بزرگ‌ترین کارخانه تولیدکننده فولاد ساختمانی و ریل در ایران است که از روش کوره بلند استفاده می‌کند.',
    backingEn: 'Audited inventory of structural steel beams, rails, and billets.',
    backingFa: 'موجودی انبار تیرآهن، ریل ساختمانی و شمش‌های فولادی با استانداردهای ملی.',
    custodianEn: 'Isfahan Central Industrial Vault',
    custodianFa: 'انبار مرکزی ذوب‌آهن و بانک ملی ایران',
    riskLevel: 'Medium',
    payoutIntervalEn: 'Annual Settlement',
    payoutIntervalFa: 'تسویه سود سالانه',
    bourseSymbol: 'ذوب',
    tsetmcUrl: 'https://tsetmc.com/instCode/12836267756828456'
  },
  {
    id: 'KHODRO',
    enName: 'Iran Khodro',
    faName: 'ایران خودرو',
    category: 'auto',
    price: 0.045,
    change: -0.5,
    flag: 'ir',
    locationEn: 'Tehran, Iran',
    locationFa: 'تهران، ایران',
    progress: 73,
    descriptionEn: 'Iran Khodro Industrial Group (IKCO) is the premier automotive manufacturer in the region with an extensive supply chain and commercial fleet assembly.',
    descriptionFa: 'گروه صنعتی ایران‌خودرو بزرگ‌ترین شرکت خودروسازی ایران و منطقه خاورمیانه است که زنجیره کامل قطعه‌سازی و مونتاژ خودرو را مدیریت می‌کند.',
    backingEn: 'Backed by commercial fleet assets and verified raw material inventory.',
    backingFa: 'پشتوانه ناوگان صنعتی و انبار قطعات و مواد اولیه شرکت.',
    custodianEn: 'IKCO Asset Trust Vault',
    custodianFa: 'صندوق امانت‌داری دارایی‌های ایران‌خودرو و بانک پارسیان',
    riskLevel: 'Medium',
    payoutIntervalEn: 'Annual Distribution',
    payoutIntervalFa: 'توزیع سود سالانه',
    bourseSymbol: 'خودرو',
    tsetmcUrl: 'https://tsetmc.com/instCode/65883838195688438'
  },
  {
    id: 'SAIPA',
    enName: 'Saipa Group',
    faName: 'سایپا',
    category: 'auto',
    price: 0.035,
    change: -0.8,
    flag: 'ir',
    locationEn: 'Tehran, Iran',
    locationFa: 'تهران، ایران',
    progress: 58,
    descriptionEn: 'Saipa Automotive Group produces economical passenger cars and light commercial vehicles with extensive domestic market penetration.',
    descriptionFa: 'شرکت خودروسازی سایپا دومین تولیدکننده بزرگ خودرو در ایران است که در حوزه ساخت خودروهای اقتصادی و تجاری سبک فعالیت می‌کند.',
    backingEn: 'Secured against production lines and finished vehicle logistics yards.',
    backingFa: 'وثیقه‌گذاری شده روی خطوط تولید و پارکینگ‌های لجستیکی خودروهای تجاری.',
    custodianEn: 'Saipa Logistics Custody',
    custodianFa: 'امانت‌داری لجستیک سایپا و بانک سپه',
    riskLevel: 'Medium',
    payoutIntervalEn: 'Annual Distribution',
    payoutIntervalFa: 'توزیع سود سالانه',
    bourseSymbol: 'خساپا',
    tsetmcUrl: 'https://tsetmc.com/instCode/24003223661676708'
  },
  {
    id: 'KHGHOSTAR',
    enName: 'Gostar Auto',
    faName: 'گسترش خودرو',
    category: 'auto',
    price: 0.062,
    change: 1.1,
    flag: 'ir',
    locationEn: 'Tabriz, Iran',
    locationFa: 'تبریز، ایران',
    progress: 49,
    descriptionEn: 'Gostar Auto Industrial Group manufactures engine casting components, heavy tractor power units, and automotive machinery in Northwest Iran.',
    descriptionFa: 'گروه صنعتی گسترش خودرو و تراکتورسازی تبریز، سازنده قطعات چدنی، موتور و ماشین‌آلات سنگین کشاورزی و صنعتی است.',
    backingEn: 'Heavy machinery and industrial engine components in certified Tabriz warehouses.',
    backingFa: 'ماشین‌آلات سنگین و قطعات موتوری صنعتی در انبارهای معتبر تبریز.',
    custodianEn: 'Tabriz Industrial Depository',
    custodianFa: 'مخزن صنعتی تبریز و بانک صادرات',
    riskLevel: 'Low',
    payoutIntervalEn: 'Semi-annual Payout',
    payoutIntervalFa: 'توزیع سود شش‌ماهه',
    bourseSymbol: 'خگستر',
    tsetmcUrl: 'https://tsetmc.com/instCode/26915124962295551'
  },
  {
    id: 'SHAPOUR',
    enName: 'Bandar Imam Petrochemical',
    faName: 'پتروشیمی بندر امام',
    category: 'petro',
    price: 0.210,
    change: 3.5,
    flag: 'ir',
    locationEn: 'Mahshahr, Iran',
    locationFa: 'ماهشهر، ایران',
    progress: 88,
    descriptionEn: 'Bandar Imam Petrochemical Company produces ethane, propane, butane, polymer grades, and aromatics strategically situated on the Persian Gulf coast.',
    descriptionFa: 'پتروشیمی بندر امام واقع در منطقه ویژه اقتصادی ماهشهر، از مجتمع‌های پیشرو در تولید پلی‌مرها، آروماتیک‌ها و گازهای مایع (LPG) است.',
    backingEn: 'Secured by physical reserves of LPG, polymers, and chemical storage tanks.',
    backingFa: 'ذخایر فیزیکی مایعات گازی (LPG)، پلیمرها و مخازن انبارش شیمیایی ساحلی.',
    custodianEn: 'Mahshahr Petro Vaults',
    custodianFa: 'خزانه‌داری پتروشیمی ماهشهر و بانک تجارت',
    riskLevel: 'Low',
    payoutIntervalEn: 'Monthly Dividend Distribution',
    payoutIntervalFa: 'توزیع سود ماهانه',
    bourseSymbol: 'پترول',
    tsetmcUrl: 'https://tsetmc.com/instCode/38321034336040700'
  },
  {
    id: 'PARSAN',
    enName: 'Parsian Oil & Gas',
    faName: 'نفت و گاز پارسیان',
    category: 'petro',
    price: 0.185,
    change: 0.4,
    flag: 'ir',
    locationEn: 'Tehran, Iran',
    locationFa: 'تهران، ایران',
    progress: 70,
    descriptionEn: 'Parsian Oil and Gas Development Company holds controlling stakes in major urea, ammonia, and refinery complexes across the country.',
    descriptionFa: 'گروه گسترش نفت و گاز پارسیان، هلدینگ تخصصی متمرکز بر پتروشیمی‌های اوره و آمونیاک و پالایشگاه‌های نفت خام کشور است.',
    backingEn: 'Portfolio backing by physical fertilizer and refined petroleum export contracts.',
    backingFa: 'پشتوانه قراردادهای صادراتی اوره، آمونیاک و فرآورده‌های پالایشی.',
    custodianEn: 'Parsian Asset Trust',
    custodianFa: 'صندوق امانت‌داری پارسیان و بانک ملت',
    riskLevel: 'Low',
    payoutIntervalEn: 'Quarterly Payout',
    payoutIntervalFa: 'توزیع سود سه‌ماهه',
    bourseSymbol: 'پارسان',
    tsetmcUrl: 'https://tsetmc.com/instCode/63892701443621453'
  },
  {
    id: 'WEBMELAT',
    enName: 'Bank Mellat',
    faName: 'بانک ملت',
    category: 'bank',
    price: 0.060,
    change: 1.5,
    flag: 'ir',
    locationEn: 'Tehran, Iran',
    locationFa: 'تهران، ایران',
    progress: 95,
    descriptionEn: 'Bank Mellat is the largest commercial bank in Iran by market capitalization, boasting high foreign exchange liquidity and digital banking services.',
    descriptionFa: 'بانک ملت بزرگ‌ترین بانک تجاری کشور از نظر ارزش بازار است که بالاترین حجم تراز ارزی و خدمات بانکی دیجیتال را ارائه می‌دهد.',
    backingEn: 'Backed by central bank reserves, commercial real estate holdings, and corporate loan portfolios.',
    backingFa: 'پشتوانه ذخایر قانونی مرکزی، املاک مرغوب تجاری و سبد تسهیلات معتبر.',
    custodianEn: 'Mellat Central Custody',
    custodianFa: 'خزانه‌داری مرکزی بانک ملت',
    riskLevel: 'Low',
    payoutIntervalEn: 'Quarterly Dividend',
    payoutIntervalFa: 'توزیع سود نقدی سه‌ماهه',
    bourseSymbol: 'وبملت',
    tsetmcUrl: 'https://tsetmc.com/instCode/34407328906935293'
  },
  {
    id: 'TEJARAT',
    enName: 'Bank Tejarat',
    faName: 'بانک تجارت',
    category: 'bank',
    price: 0.032,
    change: -0.2,
    flag: 'ir',
    locationEn: 'Tehran, Iran',
    locationFa: 'تهران، ایران',
    progress: 62,
    descriptionEn: 'Bank Tejarat plays a central role in international trade finance, letters of credit (LC), and corporate financing across major industries.',
    descriptionFa: 'بانک تجارت از ارکان اصلی اعتبارات اسنادی (LC) و تامین مالی تجارت بین‌المللی صنایع مادر در کشور است.',
    backingEn: 'Commercial credit guarantees and audited corporate collateral.',
    backingFa: 'تضامین اعتباری تجاری و وثایق حسابرسی‌شده بانکی.',
    custodianEn: 'Tejarat Central Treasury',
    custodianFa: 'خزانه‌داری مرکزی بانک تجارت',
    riskLevel: 'Medium',
    payoutIntervalEn: 'Semi-annual Distribution',
    payoutIntervalFa: 'توزیع سود شش‌ماهه',
    bourseSymbol: 'وتجارت',
    tsetmcUrl: 'https://tsetmc.com/instCode/30932232386348128'
  },
  {
    id: 'GOLD',
    enName: 'Standard Gold Reserve',
    faName: 'ذخیره شمش طلای استاندارد',
    category: 'commodities',
    price: 1200.00,
    change: 18.2,
    flag: 'ch',
    locationEn: 'Zurich, Switzerland',
    locationFa: 'زوریخ، سوئیس',
    progress: 40,
    descriptionEn: 'Allocated 100% LBMA-certified Good Delivery 24k Gold bars physically allocated in maximum-security Swiss duty-free vaults.',
    descriptionFa: 'شمش‌های طلای ۲۴ عیار استاندارد LBMA (London Bullion Market) نگهداری‌شده در خزانه‌های آزاد زوریخ سوئیس با بیمه کامل.',
    backingEn: '100% Allocated physical gold bullion stored in Zurich Canton Trust Vaults with Lloyd’s of London insurance.',
    backingFa: 'پشتوانه ۱۰۰ درصدی شمش طلای فیزیکی تخصیص‌یافته در سوئیس با پوشش بیمه لویدز لندن.',
    custodianEn: 'Zurich Canton Vaults & Malca-Amit',
    custodianFa: 'خزانه‌داری سوئیس و موسسه امانت‌داری مالکا آمیت',
    riskLevel: 'Low',
    payoutIntervalEn: 'Gold Capital Growth + Staking Yield',
    payoutIntervalFa: 'رشد ارزش طلا + سود استیکینگ دلاری'
  },
  {
    id: 'JUMEIRAH',
    enName: 'Jumeirah Beach Villa',
    faName: 'ویلا ساحلی جمیرا',
    category: 'real_estate',
    price: 250.00,
    change: 9.5,
    flag: 'ae',
    locationEn: 'Dubai, UAE',
    locationFa: 'دبی، امارات',
    progress: 82,
    descriptionEn: 'Prime beachfront luxury residential real estate in Palm Jumeirah Dubai, generating consistent high-yield USD rental income.',
    descriptionFa: 'ملک لوکس ساحلی در نخل جمیرا دبی با سند رسمی الکترونیکی DLD که اجاره‌بهای دلاری ماهانه برای داراندگان توکن به همراه دارد.',
    backingEn: 'Dubai Land Department (DLD) Title Deed & insured long-term luxury lease agreements.',
    backingFa: 'سند رسمی اداره اراضی دبی (DLD) به همراه قرارداد اجاره بلندمدت بیمه‌شده.',
    custodianEn: 'First Abu Dhabi Bank Escrow',
    custodianFa: 'حساب امانی بانک اول ابوظبی (FAB)',
    riskLevel: 'Low',
    payoutIntervalEn: 'Monthly USD Rental Dividend',
    payoutIntervalFa: 'توزیع اجاره‌بهای ماهانه به تتر'
  },
  {
    id: 'LONDON_RE',
    enName: 'London Luxury Office',
    faName: 'ساختمان اداری لندن',
    category: 'real_estate',
    price: 550.00,
    change: 6.4,
    flag: 'gb',
    locationEn: 'London, UK',
    locationFa: 'لندن، انگلستان',
    progress: 61,
    descriptionEn: 'Grade-A commercial office space located in Mayfair, London, leased to multinational corporate entities on long-term contracts.',
    descriptionFa: 'ساختمان اداری تجاری درجه A در منطقه میفر لندن که به شرکت‌های چندملیتی اجاره داده شده و سود ارزی باثبات ایجاد می‌کند.',
    backingEn: 'UK HM Land Registry title certification with multinational corporate lease covenants.',
    backingFa: 'ثبت رسمی در اداره ثبت اسناد بریتانیا (HM Land Registry) با قرارداد اجاره تضمینی.',
    custodianEn: 'Barclays Corporate Custody UK',
    custodianFa: 'بانک بارکلیز انگلستان',
    riskLevel: 'Low',
    payoutIntervalEn: 'Quarterly USD/GBP Rental Yield',
    payoutIntervalFa: 'سود اجاره سه‌ماهه ارزی'
  },
  {
    id: 'AAPL',
    enName: 'Apple Inc.',
    faName: 'اپل',
    category: 'global',
    price: 185.50,
    change: 1.2,
    flag: 'us',
    locationEn: 'California, USA',
    locationFa: 'کالیفرنیا، آمریکا',
    progress: 99,
    descriptionEn: 'Tokenized equity representing share holdings in Apple Inc., traded on NASDAQ with quarterly dividend distributions.',
    descriptionFa: 'توکن متصل به سهام واقعی شرکت اپل آمریکا در بورس نزدک با امکان دریافت سود نقدی و رشد ارزش سرمایه.',
    backingEn: '1:1 Backed by real NASDAQ stocks held in regulated US broker custody.',
    backingFa: 'پشتوانه ۱ به ۱ سهام واقعی خریداریشده در کارگزاری تحت نظارت SEC آمریکا.',
    custodianEn: 'Interactive Brokers LLC / SEC Regulated',
    custodianFa: 'امانت‌داری اینتراکتیو بروکرز آمریکا (SEC)',
    riskLevel: 'Low',
    payoutIntervalEn: 'Quarterly Cash Dividend',
    payoutIntervalFa: 'توزیع سود سه‌ماهه'
  },
  {
    id: 'TSLA',
    enName: 'Tesla Inc.',
    faName: 'تسلا',
    category: 'global',
    price: 210.00,
    change: -2.4,
    flag: 'us',
    locationEn: 'Texas, USA',
    locationFa: 'تگزاس، آمریکا',
    progress: 99,
    descriptionEn: 'Tokenized shares of Tesla Inc., global leader in electric vehicles, energy storage, and autonomous driving technology.',
    descriptionFa: 'توکن سهام شرکت تسلا پیشرو در فناوری خودروهای الکتریکی، ذخیره‌سازی انرژی و هوش مصنوعی اتونوموس.',
    backingEn: '1:1 Backed by actual NASDAQ Tesla common shares in custody.',
    backingFa: 'پشتوانه ۱ به ۱ سهام واقعی تسلا نزد کارگزاری رسمی ایالات متحده.',
    custodianEn: 'DriveWealth LLC / FINRA Custody',
    custodianFa: 'امانت‌داری درایووئلث و بانک سپردن آمریکا',
    riskLevel: 'Medium',
    payoutIntervalEn: 'Capital Growth Yield',
    payoutIntervalFa: 'رشد ارزش سرمایه'
  }
];

export const TRANSLATIONS = {
  en: {
    appName: 'AssetChain',
    tagline: 'Real World Asset Tokenization Platform',
    statusConnected: 'Mainnet Connected',
    connectWallet: 'Connect Wallet',
    disconnectWallet: 'Disconnect Wallet',
    assetsMarket: 'Assets Market',
    portfolio: 'Portfolio',
    wallet: 'Wallet',
    history: 'History',
    support: 'Support',
    aboutUs: 'About Us',
    contactUs: 'Contact Us',
    signIn: 'Sign In',
    signOut: 'Sign Out',
    signUp: 'Sign Up',
    usernameOrEmail: 'Username or Email',
    password: 'Password',
    loginError: 'Invalid credentials. Use demo / 1234',
    noAccount: "Don't have an account? Sign Up",
    hasAccount: 'Already have an account? Sign In',
    allMarkets: 'All Markets',
    categoryMetals: 'Metals',
    categoryAuto: 'Automotive',
    categoryPetro: 'Petrochemical',
    categoryBank: 'Banking',
    categoryGlobal: 'Global Shares',
    categoryRealEstate: 'Real Estate',
    categoryCommodities: 'Gold & Commodities',
    statTvl: 'Total Value Locked (TVL)',
    statApy: 'Average APY',
    statSold: 'Assets Sold',
    topInvestment: 'Top Investment Opportunities',
    tokenPrice: 'Token Price',
    expectedYield: 'Expected Growth / APY',
    saleProgress: 'Sale Progress',
    remainingUnits: 'Remaining Units',
    viewDetails: 'View Details',
    buyNow: 'Quick Buy',
    buy: 'Buy',
    sell: 'Sell',
    myPortfolio: 'My Portfolio',
    totalBalance: 'Total Assets Balance',
    totalPnl: 'Total PnL',
    recentMonth: 'Last Month',
    pnlLabel: 'PnL',
    avgCost: 'Avg Price:',
    currentPrice: 'Current Price:',
    depositUsdt: 'Deposit USDT',
    withdrawUsdt: 'Withdraw USDT',
    transactionWarning: 'All transactions are processed securely and may take up to 24h to verify.',
    selectNetwork: 'Select Network',
    depositAddress: 'Deposit Address',
    txidLabel: 'Transaction Hash (TxID)',
    txidPlaceholder: 'Paste TxID here...',
    submitDeposit: 'Submit Deposit',
    depositSuccess: 'Deposit TxID submitted! Awaiting 24h verification.',
    destinationAddress: 'Destination Address',
    destinationPlaceholder: 'Enter wallet address...',
    amountUsdt: 'Amount (USDT)',
    minAmount: 'Min 10 USDT',
    requestWithdraw: 'Request Withdraw',
    withdrawSuccess: 'Withdrawal requested! Processing within 24h.',
    transactionHistory: 'Transaction History',
    thType: 'Type & Asset',
    thAmount: 'Amount',
    thDate: 'Date',
    thStatus: 'Status',
    statusCompleted: 'Completed',
    statusPending: 'Pending',
    supportCenter: 'Support Center',
    describeIssue: 'Describe your issue',
    howCanHelp: 'How can we help you?',
    submitTicket: 'Submit Ticket',
    ticketSuccess: 'Ticket {num} submitted successfully! We will respond within 72 hours.',
    confirmBuy: 'Confirm Buy Order',
    amountToInvest: 'Amount to Invest (USDT)',
    estShares: 'Est. Shares:',
    fee: 'Fee (0.1%):',
    totalToPay: 'Total to Pay:',
    confirmSell: 'Confirm Sell Order',
    ownedShares: 'Owned: {num} Shares',
    sharesToSell: 'Shares to Sell',
    grossValue: 'Gross Value:',
    netReceive: 'Net Receive:',
    orderExecuted: 'Order executed successfully!',
    insufficientBalance: 'Insufficient USDT balance!',
    insufficientShares: 'You do not own enough shares!',
    lightMode: 'Light Mode',
    darkMode: 'Dark Mode',
    shareAndEarn: 'Invite Friends & Earn Rewards',
    referralText: 'Share your code and get 1.5% of their first asset purchase.',
    referralCode: 'Copy referral code',
    copied: 'Copied!',
    marketStatus: 'Market Status: Open',
    vol24h: 'Vol 24h: $4.2M',
    nodesActive: 'Nodes: Active',
    rightsReserved: 'All rights reserved.',
    termsAndConditions: 'Terms & Conditions',
    onlineSupport: 'Online Support',
    demoAccount: 'Demo Account Info',
    demoTip: 'Enter demo / 1234 to login and trade',
    welcomeBack: 'Welcome back,',
    enterAmount: 'Please enter a valid amount',
    home: 'Home',
    homeHeroTitle: 'Invest in Tokenized Real-World Assets (RWA)',
    homeHeroSubtitle: 'AssetChain allows you to buy fractional shares of physical gold, high-grade metals, real estate, and global blue-chip stocks with fully regulated, auditable blockchain smart contracts.',
    homeExploreBtn: 'Explore Markets',
    homeLearnMoreBtn: 'How it Works',
    homeFeatureTitle: 'Why AssetChain?',
    homeFeatureSubtitle: 'The next generation of asset ownership on-chain',
    homeFeature1Title: '100% Physical Backing',
    homeFeature1Desc: 'Every single token on AssetChain represents real, audited physical assets held safely in bank vaults and secure reserves.',
    homeFeature2Title: 'Fractional Ownership',
    homeFeature2Desc: 'Start investing with as little as 1 USDT. Access high-value real estate and luxury commodities without needing millions.',
    homeFeature3Title: 'Institutional Security',
    homeFeature3Desc: 'Regulated structures, multi-signature trust funds, and fully transparent on-chain auditing verify all active reserves.',
    homeFeature4Title: 'Instant Liquidity',
    homeFeature4Desc: 'No lock-ups. Trade your tokenized shares 24/7 on our high-performance decentralised trading engine with immediate USDT settlements.',
    homeHowItWorksTitle: 'Three Steps to On-Chain Wealth',
    homeHowStep1: '1. Deposit USDT',
    homeHowStep1Desc: 'Deposit USDT securely via TRC20, ERC20 or BEP20 networks.',
    homeHowStep2: '2. Choose Your Asset',
    homeHowStep2Desc: 'Explore our diverse marketplace containing metals, real estate, automotive, and global companies.',
    homeHowStep3: '3. Earn & Grow',
    homeHowStep3Desc: "Watch your token's physical value rise or benefit from physical rental and staking yields paid automatically.",
    assetInfoTitle: 'Asset Specifications & Backing Info',
    assetOverview: 'Asset Overview & Description',
    physicalBacking: 'Physical Backing & Legal Reserve',
    custodianTitle: 'Custodian Vault & Depository',
    riskLevelTitle: 'Risk Rating',
    payoutSchedule: 'Yield & Payout Schedule',
    smartContractInfo: 'On-Chain Token Specifications',
    closeModal: 'Close',
    proceedToBuy: 'Proceed to Buy Asset',
    assetDetailsBtn: 'Info & Specs',
    tsetmcBtn: 'TSETMC Bourse Page',
    tsetmcSectionTitle: 'Tehran Stock Exchange Info (TSETMC)',
    tsetmcDesc: 'Official real-time trading statistics, shareholder data, and order book directly from Tehran Securities Exchange Technology Management Co.'
  },
  fa: {
    appName: 'AssetChain',
    tagline: 'پلتفرم توکنایزیشن دارایی‌های دنیای واقعی (RWA)',
    statusConnected: 'شبکه اصلی متصل است',
    connectWallet: 'اتصال کیف پول',
    disconnectWallet: 'قطع اتصال',
    assetsMarket: 'بازار دارایی‌ها',
    portfolio: 'پورتفولیو',
    wallet: 'کیف پول',
    history: 'تاریخچه',
    support: 'پشتیبانی',
    aboutUs: 'درباره ما',
    contactUs: 'ارتباط با ما',
    signIn: 'ورود',
    signOut: 'خروج',
    signUp: 'ثبت‌نام',
    usernameOrEmail: 'نام کاربری یا ایمیل',
    password: 'رمز عبور',
    loginError: 'نام کاربری یا رمز عبور اشتباه است (demo / 1234)',
    noAccount: 'حساب کاربری ندارید؟ ثبت‌نام کنید',
    hasAccount: 'قبلاً ثبت‌نام کرده‌اید؟ وارد شوید',
    allMarkets: 'همه بازارها',
    categoryMetals: 'فلزات اساسی',
    categoryAuto: 'خودرو',
    categoryPetro: 'پتروشیمی',
    categoryBank: 'بانکی',
    categoryGlobal: 'سهام جهانی',
    categoryRealEstate: 'املاک و مستغلات',
    categoryCommodities: 'طلا و کالاها',
    statTvl: 'ارزش کل قفل شده (TVL)',
    statApy: 'میانگین سود سالانه',
    statSold: 'دارایی‌های فروخته شده',
    topInvestment: 'برترین فرصت‌های سرمایه‌گذاری RWA',
    tokenPrice: 'قیمت هر توکن',
    expectedYield: 'تخمین رشد / سود سالانه',
    saleProgress: 'پیشرفت فروش',
    remainingUnits: 'موجودی باقیمانده',
    viewDetails: 'مشاهده جزئیات',
    buyNow: 'خرید فوری',
    buy: 'خرید',
    sell: 'فروش',
    myPortfolio: 'پورتفولیو شما',
    totalBalance: 'موجودی کل دارایی‌ها',
    totalPnl: 'سود/زیان کل',
    recentMonth: 'ماه اخیر',
    pnlLabel: 'سود و زیان',
    avgCost: 'میانگین خرید:',
    currentPrice: 'قیمت روز:',
    depositUsdt: 'واریز تتر (USDT)',
    withdrawUsdt: 'برداشت تتر (USDT)',
    transactionWarning: 'تایید و پردازش کلیه تراکنش‌ها ممکن است تا ۲۴ ساعت زمان ببرد.',
    selectNetwork: 'انتخاب شبکه',
    depositAddress: 'آدرس واریز',
    txidLabel: 'هش تراکنش (TxID)',
    txidPlaceholder: 'کد هش تراکنش (TxID) را وارد کنید...',
    submitDeposit: 'ثبت واریزی',
    depositSuccess: 'هش تراکنش ثبت شد! در انتظار تایید ۲۴ ساعته سیستم.',
    destinationAddress: 'آدرس کیف پول مقصد',
    destinationPlaceholder: 'آدرس کیف پول مقصد را وارد کنید...',
    amountUsdt: 'مبلغ تتر (USDT)',
    minAmount: 'حداقل ۱۰ تتر',
    requestWithdraw: 'درخواست برداشت',
    withdrawSuccess: 'درخواست برداشت ثبت شد! واریز تا ۲۴ ساعت آینده.',
    transactionHistory: 'تاریخچه تراکنش‌ها',
    thType: 'نوع و دارایی',
    thAmount: 'مبلغ',
    thDate: 'تاریخ',
    thStatus: 'وضعیت',
    statusCompleted: 'تکمیل شده',
    statusPending: 'در انتظار تایید',
    supportCenter: 'مرکز پشتیبانی',
    describeIssue: 'مشکل خود را توضیح دهید',
    howCanHelp: 'چگونه می‌توانیم به شما کمک کنیم؟',
    submitTicket: 'ثبت تیکت',
    ticketSuccess: 'تیکت شماره {num} ثبت شد! حداکثر تا ۷۲ ساعت آینده پاسخ داده خواهد شد.',
    confirmBuy: 'تایید سفارش خرید',
    amountToInvest: 'مبلغ سرمایه‌گذاری (USDT)',
    estShares: 'تعداد سهم تقریبی:',
    fee: 'کارمزد (۰.۱٪):',
    totalToPay: 'پرداختی کل:',
    confirmSell: 'تایید سفارش فروش',
    ownedShares: 'موجودی: {num} سهم',
    sharesToSell: 'تعداد سهم برای فروش',
    grossValue: 'ارزش کل فروش:',
    netReceive: 'دریافتی خالص:',
    orderExecuted: 'سفارش با موفقیت انجام شد!',
    insufficientBalance: 'موجودی تتر کافی نیست!',
    insufficientShares: 'سهم کافی برای فروش ندارید!',
    lightMode: 'حالت روشن',
    darkMode: 'حالت تاریک',
    shareAndEarn: 'دعوت از دوستان و دریافت جایزه',
    referralText: 'کد دعوت خود را به اشتراک بگذارید و ۱.۵٪ از اولین خرید دارایی دوستانتان هدیه بگیرید.',
    referralCode: 'کپی کد معرف',
    copied: 'کپی شد!',
    marketStatus: 'وضعیت بازار: باز',
    vol24h: 'حجم ۲۴ ساعته: ۴.۲ میلیون دلار',
    nodesActive: 'گره‌ها: فعال',
    rightsReserved: 'تمامی حقوق محفوظ است.',
    termsAndConditions: 'قوانین و مقررات',
    onlineSupport: 'پشتیبانی آنلاین',
    demoAccount: 'اطلاعات حساب کاربری دمو',
    demoTip: 'برای ورود و معامله از نام کاربری demo و رمز عبور 1234 استفاده کنید',
    welcomeBack: 'خوش آمدید،',
    enterAmount: 'لطفاً مبلغ معتبری وارد کنید',
    home: 'صفحه اصلی',
    homeHeroTitle: 'سرمایه‌گذاری در دارایی‌های دنیای واقعی (RWA)',
    homeHeroSubtitle: 'AssetChain به شما امکان می‌دهد تا سهم‌های خرد شده‌ای از طلای فیزیکی، فلزات اساسی، املاک و مستغلات، و سهام‌های معتبر جهانی را با قراردادهای هوشمند بلاکچینی قانون‌گذاری‌شده و قابل حسابرسی خریداری کنید.',
    homeExploreBtn: 'ورود به بازارها',
    homeLearnMoreBtn: 'چگونه کار می‌کند؟',
    homeFeatureTitle: 'چرا AssetChain؟',
    homeFeatureSubtitle: 'نسل بعدی مالکیت دارایی‌ها روی زنجیره',
    homeFeature1Title: '۱۰۰٪ پشتوانه فیزیکی واقعی',
    homeFeature1Desc: 'تک تک توکن‌ها در AssetChain نماینده دارایی‌های فیزیکی واقعی و حسابرسی‌شده‌ای هستند که در خزانه‌های بانکی و ذخایر امن نگهداری می‌شوند.',
    homeFeature2Title: 'مالکیت خرد شده و ارزان',
    homeFeature2Desc: 'شروع سرمایه‌گذاری با حداقل ۱ تتر. بدون نیاز به میلیون‌ها دلار، به املاک لوکس و کالاهای گران‌بها دسترسی داشته باشید.',
    homeFeature3Title: 'امنیت در سطح سازمانی',
    homeFeature3Desc: 'ساختارهای تحت نظارت، صندوق‌های امانی چندامضایی، و حسابرسی شفاف درون‌زنجیره‌ای، تمامی ذخایر فعال را تایید می‌کنند.',
    homeFeature4Title: 'نقدشوندگی آنی و سریع',
    homeFeature4Desc: 'بدون دوره بلوکه شدن. دارایی‌های توکنایز شده خود را ۲۴ ساعته در موتور معاملاتی فوق‌سریع ما معامله کنید و آنی تسویه تتر بگیرید.',
    homeHowItWorksTitle: '۳ مرحله ساده برای مالکیت دارایی‌های واقعی',
    homeHowStep1: '۱. شارژ حساب تتر',
    homeHowStep1Desc: 'حساب خود را به صورت امن با تتر از طریق شبکه‌های TRC20، ERC20 یا BEP20 شارژ کنید.',
    homeHowStep2: '۲. انتخاب دارایی دلخواه',
    homeHowStep2Desc: 'بازار متنوع ما شامل فلزات، املاک، خودرو و شرکت‌های بزرگ جهانی را بررسی و دارایی مورد نظر را انتخاب کنید.',
    homeHowStep3: '۳. دریافت سود و رشد',
    homeHowStep3Desc: 'رشد ارزش دارایی فیزیکی خود را مشاهده کنید یا از اجاره‌بها و سودهای پرداختی بهره‌مند شوید.',
    assetInfoTitle: 'مشخصات کامل و اطلاعات پشتوانه دارایی',
    assetOverview: 'معرفی و توضیحات جامع دارایی',
    physicalBacking: 'پشتوانه فیزیکی و امانت‌داری قانونی',
    custodianTitle: 'امانت‌دار، خزانه و بانک نگه‌دارنده',
    riskLevelTitle: 'درجه ریسک سرمایه‌گذاری',
    payoutSchedule: 'برنامه و نحوه پرداخت سود / اجاره‌بها',
    smartContractInfo: 'مشخصات قرارداد هوشمند و توکن روی زنجیره',
    closeModal: 'بستن',
    proceedToBuy: 'ورود به صفحه خرید این دارایی',
    assetDetailsBtn: 'اطلاعات و مشخصات',
    tsetmcBtn: 'اطلاعات جامع سهم در TSETMC',
    tsetmcSectionTitle: 'صفحه نماد در بورس تهران (TSETMC)',
    tsetmcDesc: 'مشاهده تابلو آنلاین نماد، حجم معاملات، خریداران حقیقی و حقوقی و گزارش‌های رسمی در سایت مدیریت فناوری بورس تهران.'
  }
};
